# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
- main
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'

pool:
  name: Default

stages:

- stage: Build_and_Push
  variables:
   - group: secrets
   - group: acr_variables
  jobs:
  - job: Build_and_Push_Job
    steps:
    - checkout: self
    - script: |
        # Authenticate with Azure CLI
        az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
        az acr login --name $(TF_VAR_PRIVATE_ACR_NAME)

        # Sanitize repo name to lowercase for Docker tag compliance
        REPO_NAME=$(echo "$(build.repository.name)" | tr '[:upper:]' '[:lower:]')
        BRANCH_NAME=$(echo "$(Build.SourceBranchName)" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG="${REPO_NAME}-${BRANCH_NAME}:v1"

        echo "Building image: $(TF_VAR_PRIVATE_ACR_NAME).azurecr.io/${IMAGE_TAG}"

        # Build and push the Docker image to ACR
        docker build -t $(TF_VAR_PRIVATE_ACR_NAME).azurecr.io/${IMAGE_TAG} .
        docker push $(TF_VAR_PRIVATE_ACR_NAME).azurecr.io/${IMAGE_TAG}
      displayName: 'Build and Push Docker Image'

- stage: Deploy_to_AKS
  variables:
    - group: secrets
  jobs:
  - deployment: Deploy_to_AKS_Job
    environment: 'AKS_Environment'
    pool:
      name: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              # Authenticate with Azure CLI
              az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
              az aks get-credentials --resource-group terraform-state-rg --name aksdemo --overwrite-existing
              # Deploy to AKS
              kubectl apply -f deployment.yaml
            displayName: 'Deploy to AKS'
